#!/bin/bash
#SBATCH --job-name=bioinformatic_pipeline #job name
#SBATCH --output=./bioinformatic_pipeline.out # output
#SBATCH --error=./bioinformatic_pipeline.err # error
#SBATCH --time=48:00:00 # max runtime
#SBATCH --ntasks=1 #number of tasks
#SBATCH --cpus-per-task=8 # no of CPUs per tasks
#SBATCH --mem=100G

module load python/3.10.8
module load bioinformatics
module load filtlong/0.2.1
module load flye/2.9.2
module load prokka/1.14.6
module load samtools
module load minimap2
module load nanoplot

mkdir -p ./Nanoplot_DC02
mkdir -p ./Flye_DC02
mkdir -p ./Prokka_DC02
mkdir -p .Filtlong_DC02

samtools view -b -f 4 ./dorado_demux_run2/48ff95e8b5ab9529617943432bf77443961cb71f_Sample1.bam > ./unmapped_DC02.bam
samtools fastq ./unmapped_DC02.bam > ./unmapped_DC02.fastq

NanoPlot --fastq ./unmapped_DC02.fastq --outdir ./Nanoplot_DC02

cd ./Filtlong_DC02
filtlong --min_length 1000 --min_mean_q 10 --target_bases 5000000000 ./unmapped_DC02.fastq > ./filtered_DC02.fastq

cd ./
flye --meta --nano-raw ./filtered_DC02.fastq --out-dir ./Flye_DC02

prokka --outdir ./Prokka_DC02 --prefix 1 --force ./Flye_DC02/assembly.fasta

minimap2 -ax map-ont ./Flye_DC02/assembly.fasta ./filtered_DC02.fastq | samtools sort -o ./aligned_DC02.bam
samtools index ./aligned_DC02.bam

module load bedtools

bedtools bamtobed -i ./aligned_DC02.bam > ./mydata_DC02.bed

module load kraken2
module load krakentools
mkdir -p /nobackup/vdvk82/Kraken_DC02
kraken2 --db ./my_kraken_db --output ./Kraken_DC02/classification.txt --report ./Kraken_DC02/report.txt ./Flye_DC02/assembly.fasta

cd ./
module load maxbin2
run_MaxBin.pl
mkdir -p ./maxbin_output_DC02

run_MaxBin.pl -contig ./Flye_DC02/assembly.fasta -abund ./depth_DC02.txt -out ./maxbin_output_DC02

mkdir -p ./prokka_bin_DC02

for bin in ./maxbin_output_DC02/*.fa ./maxbin_output_DC02/*.fna; do
    BIN_NAME=$(basename "$bin" | sed 's/\.[^.]*$//')
    prokka --outdir ./prokka_bin_DC02 --force --prefix "${BIN_NAME}_annotation" "$bin"
done

mkdir -p ./Kraken_bins_DC02
for bin in ./maxbin_output_DC02/*.fa ./maxbin_output_DC02/*.fna; do
    if [[ -f "$bin" ]]; then
        BIN_NAME=$(basename "$bin" | sed 's/\.[^.]*$//')

         kraken2 \
            --db ./my_kraken_db \
            --threads 8 \
            --report "./Kraken_bins_DC02/${BIN_NAME}_report.txt" \
            --output "./Kraken_bins_DC02/${BIN_NAME}_kraken_output.txt" \
            --use-names "$bin"

              echo "Finished processing $BIN_NAME!"
    fi
done

echo "All bins processed successfully!"
module load mafft
for i in $(seq -w 1 12); do
  input="./checkM_output_DC02/bins/maxbin.${i}/genes.faa"
  output="./mafft_DC02/${i#0}_genes_aligned.faa"
  mafft --auto "$input" > "$output"
done

module load mash

mkdir -p ./mash
cd ./

mash sketch -o ./mash/all.msh ./mags_for_mash/*.fasta
mash dist ./all.msh > ./distances.tab
